export const DESCARGAR_LIBROS = 'DESCARGAR_LIBROS';
export const DESCARGAR_LIBROS_EXITO = 'DESCARGAR_LIBROS_EXITO';
export const DESCARGAR_LIBROS_ERROR = 'DESCARGAR_LIBROS_ERROR';
export const OBTENER_DETALLE_LIBRO = 'OBTENER_DETALLE_LIBRO';
export const OBTENER_DETALLE_LIBROAPI = 'OBTENER_DETALLE_LIBROAPI';
export const OBTENER_DETALLE_LIBRO_ERROR = 'OBTENER_DETALLE_LIBRO_ERROR';
export const INCREMENTAR_PAGINA_ACTUAL = 'INCREMENTAR_PAGINA_ACTUAL';
export const DECREMENTAR_PAGINA_ACTUAL = 'DECREMENTAR_PAGINA_ACTUAL';

export const DESCARGAR_LIBROS_CATEGORIAS = 'DESCARGAR_LIBROS_CATEGORIAS';
export const DESCARGAR_LIBROS_CATEGORIAS_EXITO = 'DESCARGAR_LIBROS_CATEGORIAS_EXITO';
export const DESCARGAR_LIBROS_CATEGORIAS_ERROR = 'DESCARGAR_LIBROS_CATEGORIAS_ERROR';

export const DESCARGAR_LIBROS_SOLICITADOS = 'DESCARGAR_LIBROS_SOLICITADOS';
export const DESCARGAR_LIBROS_SOLICITADOS_EXITO = 'DESCARGAR_LIBROS_SOLICITADOS_EXITO';
export const DESCARGAR_LIBROS_SOLICITADOS_ERROR = 'DESCARGAR_LIBROS_SOLICITADOS_ERROR';


export const DESCARGAR_LIBROS_AUTOR = 'DESCARGAR_LIBROS_AUTOR';
export const DESCARGAR_LIBROS_AUTOR_EXITO = 'DESCARGAR_LIBROS_AUTOR_EXITO';
export const DESCARGAR_LIBROS_AUTOR_ERROR = 'DESCARGAR_LIBROS_AUTOR_ERROR';

export const DESCARGAR_CATEGORIAS = 'DESCARGAR_CATEGORIAS';
export const DESCARGAR_CATEGORIAS_EXITO = 'DESCARGAR_CATEGORIAS_EXITO';
export const DESCARGAR_CATEGORIAS_ERROR = 'DESCARGAR_CATEGORIAS_ERROR';

export const DESCARGAR_AUTORES = 'DESCARGAR_AUTORES';
export const DESCARGAR_AUTORES_EXITO = 'DESCARGAR_AUTORES_EXITO';
export const DESCARGAR_AUTORES_ERROR = 'DESCARGAR_AUTORES_ERROR';

export const DESCARGAR_DETALLE_LIBRO = 'DESCARGAR_DETALLE_LIBRO';
export const DESCARGAR_DETALLE_LIBRO_EXITO = 'DESCARGAR_DETALLE_LIBRO_EXITO';
export const DESCARGAR_DETALLE_LIBRO_ERROR = 'DESCARGAR_DETALLE_LIBRO_ERROR';

export const CALIFICAR_LIBRO_EXITO = 'CALIFICAR_LIBRO_EXITO';
export const CALIFICAR_LIBRO_ERROR = 'CALIFICAR_LIBRO_ERROR';

export const SOLICITAR_LIBRO_EXITO = 'SOLICITAR_LIBRO_EXITO';
export const SOLICITAR_LIBRO_ERROR = 'SOLICITAR_LIBRO_ERROR';


export const GUARDAR_CATEGORIAS_SELECCIONADAS = 'GUARDAR_CATEGORIAS_SELECCIONADAS';
export const GUARDAR_AUTORES_SELECCIONADOS = 'GUARDAR_AUTORES_SELECCIONADOS';
export const GUARDAR_BUSQUEDA_SELECCIONADA = 'GUARDAR_BUSQUEDA_SELECCIONADA';
